// Generated by https://pagedraw.io/pages/13216
import React from 'react';
import './keyvaluetext.css';


export default class Keyvaluetext extends React.Component {
  render() {
    return (
      <div className="keyvaluetext-keyvaluetext-8">
          <div className="keyvaluetext-0">
              <div className="keyvaluetext-key_-5">
                  { this.props.label }
              </div>
              <div className="keyvaluetext-value_-6">
                  { this.props.value }
              </div>
          </div>
      </div>
    );
  }
};
