// Generated by https://pagedraw.io/pages/13216
import React from 'react';
import Colorcard from './colorcard';
import './resultslist.css';


export default class Resultslist extends React.Component {
  render() {
    return (
      <div className="resultslist-resultslist-2">
          <div className="resultslist-0">
              <div className="resultslist-colorcard_instance-1">
                  <Colorcard name={""} number={""} locator={""} color={"rgb(147, 67, 67)"} /> 
              </div>
          </div>
          <div className="resultslist-1">
              <div className="resultslist-colorcard_instance_2">
                  <Colorcard name={""} number={""} locator={""} color={"#ffffff"} /> 
              </div>
          </div>
          <div className="resultslist-2" /> 
      </div>
    );
  }
};
